default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= Gem.win_platform? ? 'json-api-example' : nil %>
  password: <%= Gem.win_platform? ? 'only_need_in_windows' : nil %>

development:
  <<: *default
  database: json-api-example_development
  host: localhost

test:
  <<: *default
  database: json-api-example_test
  host: localhost
